[project]
name = "pdf-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "pymupdf>=1.26.1",
    "pywebview>=5.4",
]
